/* Year 7 weekly words: 40 weeks × 10 words, with a simple meaning and an example sentence.
   Chosen from the vocabulary Key Stage 3 pupils meet across subjects (academic "tier 2" words,
   subject words and commonly misspelt words). Week 1 starts on WEEK1 below; a new list opens every Monday. */
"use strict";
const WEEK1="2026-09-28";
const WEEK_WORDS=[
["Starting secondary school",[
["timetable","A plan showing what lessons happen at which times.","I checked my timetable to see if we had science after lunch."],
["independent","Able to do things by yourself without help.","Secondary school helps you become more independent."],
["responsible","In charge of something and trusted to do it properly.","Each pupil is responsible for bringing the right books."],
["organise","To arrange things in a sensible order.","I organise my bag the night before school."],
["schedule","A list of times when things are planned to happen.","The trip schedule says the coach leaves at eight."],
["equipment","The tools or things you need for a job or activity.","Bring your PE equipment on Tuesdays."],
["register","An official list of names, often checked to see who is present.","Our tutor takes the register every morning."],
["curriculum","All the subjects and topics taught at a school.","Computing is part of the Year 7 curriculum."],
["opportunity","A chance to do something.","The school play is a great opportunity to make friends."],
["achievement","Something good that you have done through hard work.","Getting into the football team was a big achievement."]]],
["Words for explaining",[
["explain","To make something clear by giving details or reasons.","Can you explain how you got that answer?"],
["describe","To say what something is like.","Describe the setting of the story in three sentences."],
["identify","To recognise and name something.","Identify the verbs in this paragraph."],
["define","To say exactly what a word or idea means.","Define the word 'habitat' in your own words."],
["illustrate","To show or explain something with pictures or examples.","Use a diagram to illustrate the water cycle."],
["summarise","To give the main points in a short form.","Summarise the chapter in fifty words."],
["outline","To give the main facts without the details.","Outline the causes of the Great Fire of London."],
["clarify","To make something easier to understand.","The teacher clarified the instructions."],
["example","Something that shows what others of the same kind are like.","A robin is an example of a garden bird."],
["detail","A small fact or piece of information.","Add more detail to make your description vivid."]]],
["Words for thinking",[
["analyse","To look at something closely to understand it.","We analysed the poem line by line."],
["consider","To think carefully about something.","Consider both sides before you decide."],
["evaluate","To judge how good or useful something is.","Evaluate how well your experiment worked."],
["interpret","To decide what something means.","People can interpret the ending in different ways."],
["predict","To say what you think will happen.","Predict what the character will do next."],
["compare","To look at how things are similar and different.","Compare the two maps of the town."],
["contrast","To show the differences between things.","The writer contrasts the busy city with the quiet village."],
["assume","To believe something is true without proof.","Don't assume the answer is obvious."],
["conclude","To decide something after thinking about the facts.","We concluded that plants need light to grow."],
["reflect","To think carefully about something you have done.","Reflect on what you would improve next time."]]],
["Persuasive writing",[
["persuade","To make someone agree with you or do something.","She persuaded her parents to adopt a puppy."],
["argument","A set of reasons given to show something is true.","His argument was supported by clear evidence."],
["opinion","What someone thinks or believes about something.","In my opinion, homework should be shorter."],
["evidence","Facts or information that show something is true.","Use evidence from the text to support your answer."],
["convince","To make someone believe that something is true.","The advert tried to convince us to buy the phone."],
["audience","The people who read, watch or listen to something.","Think about your audience when you write a speech."],
["rhetorical","Used for effect, not expecting an answer.","'Who doesn't love chocolate?' is a rhetorical question."],
["emphasise","To show that something is especially important.","Bold text can emphasise a key word."],
["counter-argument","A reason given against another argument.","A strong essay answers the counter-argument."],
["therefore","For that reason; as a result.","It was raining; therefore, the match was cancelled."]]],
["Story writing",[
["narrative","A story or a description of events.","Write a narrative about a lost key."],
["character","A person or animal in a story.","The main character is brave but stubborn."],
["setting","The place and time where a story happens.","The setting is a foggy harbour in winter."],
["atmosphere","The feeling or mood of a place or scene.","The writer creates a tense atmosphere."],
["dialogue","The words that characters say to each other.","Use speech marks around dialogue."],
["tension","A feeling of worry or excitement about what will happen.","Short sentences build tension."],
["climax","The most exciting or important point of a story.","The climax comes when the bridge collapses."],
["resolution","How the problem in a story is solved at the end.","The resolution was happy and satisfying."],
["protagonist","The main character in a story.","The protagonist must choose between two friends."],
["perspective","A particular way of seeing things.","The story is told from the dog's perspective."]]],
["Language techniques",[
["simile","A comparison using 'like' or 'as'.","'As quiet as a mouse' is a simile."],
["metaphor","Describing something as if it were something else.","'The classroom was a zoo' is a metaphor."],
["personification","Giving human qualities to a thing or idea.","'The wind whispered' is personification."],
["alliteration","Words close together that start with the same sound.","'Silent snakes slithered' uses alliteration."],
["onomatopoeia","A word that sounds like the noise it describes.","'Buzz' and 'crash' are examples of onomatopoeia."],
["imagery","Language that creates pictures in the reader's mind.","The poem's imagery made me picture the sea."],
["hyperbole","Exaggeration used for effect.","'I've told you a million times' is hyperbole."],
["symbolism","Using an object to stand for an idea.","The dove is often used as symbolism for peace."],
["repetition","Saying or writing something more than once for effect.","Repetition makes the speech memorable."],
["tone","The feeling or attitude shown in writing.","The tone of the letter is angry."]]],
["Grammar words",[
["noun","A word for a person, place, thing or idea.","'Happiness' is an abstract noun."],
["adjective","A word that describes a noun.","'Enormous' is a powerful adjective."],
["adverb","A word that describes how, when or where something happens.","'Quickly' is an adverb."],
["preposition","A word showing position or time, like 'under' or 'after'.","'Beneath' is a preposition."],
["conjunction","A word that joins parts of a sentence, like 'because'.","Use a conjunction to join the two ideas."],
["pronoun","A word used instead of a noun, like 'she' or 'it'.","Replace the name with a pronoun."],
["clause","A group of words with a subject and a verb.","'When the bell rang' is a subordinate clause."],
["paragraph","A group of sentences about one idea.","Start a new paragraph when the time changes."],
["punctuation","Marks such as commas and full stops used in writing.","Check your punctuation before you hand it in."],
["apostrophe","A mark (') showing missing letters or belonging.","'Don't' needs an apostrophe."]]],
["Tricky spellings 1",[
["necessary","Needed; essential.","It is necessary to wear goggles in the lab."],
["separate","Apart; not joined together.","Keep the wet clothes separate from the dry ones."],
["definitely","Certainly; without any doubt.","I will definitely finish my project tonight."],
["environment","The natural world, or the surroundings you live in.","We must protect the environment."],
["government","The group of people who run a country.","The government announced a new law."],
["beginning","The start of something.","The beginning of the book is exciting."],
["believe","To think that something is true.","I believe you are telling the truth."],
["business","Work that involves buying and selling; a company.","Her aunt runs a cake business."],
["disappear","To go out of sight.","The sun disappeared behind the clouds."],
["embarrass","To make someone feel awkward or ashamed.","Please don't embarrass me in front of my friends."]]],
["Science in the lab",[
["experiment","A test done to find out something.","Our experiment tested which material keeps ice frozen longest."],
["hypothesis","An idea that can be tested by an experiment.","My hypothesis is that warmer water dissolves sugar faster."],
["variable","A factor that can change in an experiment.","Temperature is the variable we are changing."],
["apparatus","The equipment used for a science experiment.","Set up the apparatus carefully."],
["observation","Something you notice by watching closely.","Record every observation in your table."],
["measurement","A size or amount found by measuring.","Take each measurement three times."],
["accurate","Correct and exact.","Use a ruler to get an accurate reading."],
["reliable","Able to be trusted; giving the same result each time.","Repeating the test makes results more reliable."],
["method","The steps used to do something.","Write the method as a numbered list."],
["conclusion","What you decide after looking at the results.","Your conclusion should answer the question."]]],
["Cells and living things",[
["organism","A living thing.","A bacterium is a tiny organism."],
["cell","The smallest unit of a living thing.","Plant cells have a cell wall."],
["nucleus","The part of a cell that controls it.","The nucleus contains genetic material."],
["membrane","A thin layer that surrounds a cell.","The membrane controls what enters the cell."],
["tissue","A group of similar cells working together.","Muscle tissue helps you move."],
["organ","A part of the body that does a particular job.","The heart is an organ that pumps blood."],
["microscope","An instrument that makes tiny things look bigger.","We looked at onion cells under a microscope."],
["photosynthesis","How plants make food using sunlight.","Photosynthesis takes place in the leaves."],
["respiration","How living things release energy from food.","Respiration happens in every living cell."],
["reproduce","To produce young or new copies.","Flowering plants reproduce using seeds."]]],
["Forces and energy",[
["force","A push or a pull.","Gravity is a force that pulls things down."],
["gravity","The force that pulls objects towards each other.","Gravity keeps the Moon in orbit."],
["friction","A force that slows things down when surfaces rub.","Friction between the tyres and road helps the bike stop."],
["resistance","A force that works against movement.","Air resistance slows a parachute down."],
["energy","The ability to do work or make things happen.","Food gives us energy."],
["transfer","To move something from one place to another.","Energy is transferred from the battery to the bulb."],
["mass","The amount of matter in an object.","Mass is measured in kilograms."],
["weight","The force of gravity on an object.","Your weight would be smaller on the Moon."],
["balanced","Equal on both sides, so nothing changes.","Balanced forces keep the book still."],
["accelerate","To get faster.","The car accelerated as the lights turned green."]]],
["History and time",[
["century","A period of one hundred years.","The castle was built in the twelfth century."],
["chronological","Arranged in the order that events happened.","Put the events in chronological order."],
["source","Something that gives information about the past.","A diary is a useful historical source."],
["primary","First-hand; from the time being studied.","A letter written in 1066 is a primary source."],
["secondary","Second-hand; made later about the past.","A modern textbook is a secondary source."],
["empire","A group of countries ruled by one ruler or country.","The Roman Empire stretched across Europe."],
["monarch","A king or queen.","The monarch opened Parliament."],
["invasion","When an army enters a country to take control.","The Norman invasion happened in 1066."],
["medieval","From the Middle Ages, about 1000 to 1500.","Medieval towns had narrow streets."],
["significant","Important or large enough to matter.","The printing press was a significant invention."]]],
["Medieval England",[
["feudal","Describing a system where people gave service in return for land.","The feudal system put the king at the top."],
["peasant","A poor farm worker in the past.","Most peasants worked on their lord's land."],
["baron","A powerful noble in the Middle Ages.","The barons forced King John to sign Magna Carta."],
["castle","A large strong building with thick walls.","The castle was built to control the town."],
["siege","When an army surrounds a place to make it surrender.","The siege lasted six months."],
["rebellion","An attempt to fight against those in power.","The Peasants' Revolt was a rebellion in 1381."],
["plague","A disease that spreads quickly and kills many people.","The Black Death was a terrible plague."],
["pilgrim","A person who travels to a holy place.","Pilgrims travelled to Canterbury."],
["chronicle","A written record of events in time order.","Monks wrote chronicles of each year."],
["authority","The power to give orders.","The Church had great authority."]]],
["Geography words",[
["continent","One of the seven large areas of land on Earth.","Africa is the second-largest continent."],
["population","The number of people living in a place.","The population of London is about nine million."],
["climate","The usual weather in a place over many years.","Britain has a mild climate."],
["landscape","Everything you can see across an area of land.","The landscape was flat and green."],
["erosion","The wearing away of land by water, wind or ice.","Erosion has shaped the cliffs."],
["settlement","A place where people live, such as a village or town.","The settlement grew up beside the river."],
["urban","To do with towns and cities.","Urban areas are often busy and crowded."],
["rural","To do with the countryside.","She lives in a rural village."],
["latitude","How far north or south a place is from the equator.","Lines of latitude run east to west."],
["sustainable","Able to continue without harming the environment.","Wind power is a sustainable energy source."]]],
["Weather and climate",[
["temperature","How hot or cold something is.","The temperature fell below zero."],
["precipitation","Water falling from the sky as rain, snow or hail.","Precipitation is high in the west of Britain."],
["humid","Warm and damp.","The rainforest is hot and humid."],
["drought","A long period with little or no rain.","The drought dried up the reservoir."],
["forecast","A statement about what the weather will be.","The forecast says it will snow tomorrow."],
["visibility","How far you can see, especially in bad weather.","Thick fog reduced visibility to ten metres."],
["evaporate","To change from liquid into gas.","Puddles evaporate on a sunny day."],
["condensation","Water that forms when vapour cools.","Condensation covered the cold window."],
["extreme","Very great or severe.","Extreme weather is becoming more common."],
["environmental","To do with the natural world.","Pollution is an environmental problem."]]],
["Maths words",[
["calculate","To work out an answer using numbers.","Calculate the area of the rectangle."],
["estimate","To make a sensible guess at an amount.","Estimate the answer before you work it out."],
["equation","A statement that two things are equal, with an equals sign.","Solve the equation 2x + 3 = 11."],
["expression","A group of numbers, letters and symbols without an equals sign.","Simplify the expression 3a + 2a."],
["formula","A rule written with letters and symbols.","The formula for area is length × width."],
["perimeter","The distance all the way round a shape.","The perimeter of the field is 400 metres."],
["parallel","Always the same distance apart and never meeting.","Railway tracks are parallel."],
["perpendicular","At a right angle to another line.","The wall is perpendicular to the floor."],
["probability","How likely something is to happen.","The probability of rolling a six is 1/6."],
["approximately","Roughly; not exactly.","The journey takes approximately two hours."]]],
["Tricky spellings 2",[
["accommodate","To provide space for; to have room for.","The hall can accommodate 300 people."],
["occasionally","Sometimes, but not often.","We occasionally go swimming after school."],
["recommend","To suggest that something is good.","I recommend this book to anyone who likes mysteries."],
["committee","A group of people chosen to make decisions.","The school committee planned the fair."],
["exaggerate","To make something seem bigger or more important than it is.","Don't exaggerate how long you waited."],
["immediately","At once; straight away.","Leave the building immediately when the alarm rings."],
["parliament","The group of elected people who make a country's laws.","Parliament meets in Westminster."],
["guarantee","A promise that something will happen.","There's no guarantee it will be sunny."],
["rhythm","A regular pattern of sounds or beats.","Clap the rhythm of the song."],
["conscience","The feeling inside you that tells you what is right and wrong.","My conscience told me to own up."]]],
["Feelings and character",[
["anxious","Worried and nervous.","She felt anxious before the test."],
["confident","Sure of yourself and your abilities.","He was confident he could climb the wall."],
["determined","Having decided firmly to do something.","She was determined to win the race."],
["reluctant","Not wanting to do something.","He was reluctant to leave the party."],
["generous","Happy to give or share.","It was generous of you to lend me your pens."],
["sympathetic","Showing that you understand someone's feelings.","My friend was sympathetic when my pet died."],
["arrogant","Behaving as if you are better than others.","The arrogant knight ignored the advice."],
["resilient","Able to recover quickly from difficulties.","Resilient people keep trying after a setback."],
["curious","Wanting to know or learn something.","The curious cat explored the box."],
["frustrated","Annoyed because you cannot do what you want.","I felt frustrated when my computer froze."]]],
["Describing places",[
["ancient","Very old; from long ago.","We explored an ancient stone circle."],
["desolate","Empty, lonely and bleak.","The moor was desolate in winter."],
["bustling","Full of busy activity.","The market was bustling with shoppers."],
["picturesque","Pretty, like a picture.","The picturesque village had thatched cottages."],
["derelict","Empty and in very bad condition.","The derelict factory had broken windows."],
["tranquil","Calm and peaceful.","The lake was tranquil at dawn."],
["looming","Appearing large and threatening.","Dark clouds were looming over the hills."],
["vast","Extremely large.","A vast desert stretched before them."],
["eerie","Strange and frightening.","An eerie silence filled the house."],
["majestic","Grand and impressive.","The majestic mountains were covered in snow."]]],
["Words for time and order",[
["previously","Before now; earlier.","Previously, the school had no library."],
["subsequently","Afterwards; later.","He fell and subsequently went to hospital."],
["meanwhile","At the same time; while something else happens.","Meanwhile, back at the castle, the king slept."],
["eventually","In the end, after a long time.","Eventually, the rain stopped."],
["initially","At the beginning.","Initially I was nervous, but I soon relaxed."],
["simultaneously","At exactly the same time.","Two runners crossed the line simultaneously."],
["frequently","Often.","Buses run frequently in the city."],
["temporary","Lasting for only a short time.","The classroom is in a temporary building."],
["permanent","Lasting for ever or for a very long time.","The tattoo is permanent."],
["sequence","A set of things in a particular order.","Follow the sequence of steps carefully."]]],
["Words for argument and debate",[
["debate","A formal discussion where people give different views.","We had a debate about school uniform."],
["controversial","Causing a lot of disagreement.","The new rule was controversial."],
["justify","To give good reasons for something.","Justify your answer with evidence."],
["bias","Unfairly favouring one side.","The article showed bias towards one team."],
["objective","Based on facts, not feelings.","A report should be objective."],
["subjective","Based on personal feelings or opinions.","Film reviews are often subjective."],
["valid","Reasonable and acceptable.","That is a valid point."],
["contradict","To say the opposite of something.","His actions contradict what he says."],
["acknowledge","To accept or admit that something is true.","She acknowledged that she was wrong."],
["consequence","A result of an action.","Missing homework has consequences."]]],
["Shakespeare and drama",[
["playwright","A person who writes plays.","Shakespeare is England's most famous playwright."],
["tragedy","A serious play with a sad ending.","Romeo and Juliet is a tragedy."],
["comedy","A play or film meant to make people laugh, often with a happy ending.","A Midsummer Night's Dream is a comedy."],
["soliloquy","A speech in which a character speaks their thoughts aloud alone.","Hamlet's soliloquy begins 'To be, or not to be'."],
["stage directions","Instructions in a script telling actors what to do.","The stage directions say 'Enter a ghost'."],
["villain","The bad character in a story or play.","The villain plotted against the king."],
["monologue","A long speech by one character.","The actor learned a two-minute monologue."],
["rehearsal","A practice before a performance.","We had a rehearsal every lunchtime."],
["dramatic irony","When the audience knows something a character does not.","Dramatic irony builds suspense."],
["prologue","An opening speech or section that introduces a story.","The prologue tells us the lovers will die."]]],
["Poetry words",[
["stanza","A group of lines in a poem, like a paragraph.","The poem has four stanzas."],
["rhyme","Words that end with the same sound.","'Light' and 'night' rhyme."],
["verse","Writing arranged in lines with rhythm.","The story was told in verse."],
["syllable","A part of a word with one vowel sound.","'Butterfly' has three syllables."],
["sonnet","A poem of fourteen lines.","Shakespeare wrote 154 sonnets."],
["haiku","A short Japanese poem of three lines.","A haiku has five, seven and five syllables."],
["enjambment","When a sentence runs on from one line of poetry to the next.","Enjambment makes the poem flow."],
["couplet","Two lines of poetry next to each other, often rhyming.","The sonnet ends with a rhyming couplet."],
["narrator","The person who tells a story or poem.","The narrator is a young soldier."],
["theme","The main idea or message of a text.","Friendship is a theme in the poem."]]],
["Technology and computing",[
["algorithm","A set of step-by-step instructions to solve a problem.","We wrote an algorithm to sort the numbers."],
["program","A set of instructions that a computer follows.","My program draws a square."],
["software","Programs used by a computer.","The school bought new design software."],
["hardware","The physical parts of a computer.","The keyboard and screen are hardware."],
["network","A group of connected computers.","The school network was down."],
["data","Facts and information, often stored on a computer.","We collected data about pupils' favourite sports."],
["binary","A number system that uses only 0 and 1.","Computers store information in binary."],
["password","A secret word used to get into an account.","Never share your password."],
["digital","Using computer technology; using numbers.","Most photos are now digital."],
["innovation","A new idea, method or invention.","The smartphone was a major innovation."]]],
["Online safety and media",[
["privacy","Keeping your personal information to yourself.","Check your privacy settings online."],
["reputation","What people think about someone or something.","Posts online can affect your reputation."],
["anonymous","Without a name being given.","The note was anonymous."],
["credible","Able to be believed; trustworthy.","Check whether a website is credible before you use it."],
["misleading","Giving the wrong idea.","The headline was misleading."],
["influence","The power to change how someone thinks or acts.","Adverts influence what we buy."],
["advertisement","A notice or video that tries to sell something.","The advertisement promised amazing results."],
["communicate","To share information with others.","We communicate by text and email."],
["appropriate","Suitable or right for a situation.","Use appropriate language in emails."],
["consent","Permission for something to happen.","Ask for consent before posting a photo of a friend."]]],
["Art and music",[
["composition","The way parts of a picture or piece of music are arranged.","The composition of the painting draws your eye to the centre."],
["abstract","Art that uses shapes and colours rather than showing real things.","The abstract painting was full of swirling colours."],
["texture","How something feels or looks as if it feels.","The artist added texture with thick paint."],
["palette","The range of colours an artist uses, or the board for mixing paint.","Her palette was mostly blues and greens."],
["tempo","The speed of a piece of music.","The tempo gets faster at the end."],
["melody","A tune.","She hummed the melody of the song."],
["harmony","Notes played together that sound pleasant.","The choir sang in harmony."],
["orchestra","A large group of musicians playing together.","The orchestra has strings, brass and percussion."],
["sculpture","A piece of art made by shaping materials.","The sculpture was made of bronze."],
["portrait","A picture of a person.","Rembrandt painted many self-portraits."]]],
["Sport and health",[
["athlete","A person who is good at sport and trains hard.","The athlete trained every morning."],
["stamina","The energy to keep going for a long time.","Long-distance running builds stamina."],
["nutrition","The food your body needs to stay healthy.","Good nutrition helps you concentrate."],
["muscle","Body tissue that tightens and relaxes to move you.","Stretch your muscles before exercise."],
["flexible","Able to bend easily without breaking.","Gymnasts are very flexible."],
["competition","An event where people try to win.","Our school won the swimming competition."],
["tournament","A series of games to find a winner.","The tournament lasted two days."],
["opponent","The person or team you play against.","She shook hands with her opponent."],
["technique","A way of doing something skilfully.","Practise your passing technique."],
["recovery","Getting back to normal after illness or effort.","Sleep is important for recovery."]]],
["Tricky spellings 3",[
["achieve","To succeed in doing something.","You can achieve anything with practice."],
["awkward","Clumsy, or uncomfortable and embarrassing.","There was an awkward silence after the joke."],
["especially","More than usual; particularly.","I love fruit, especially mangoes."],
["foreign","From or in another country.","She speaks two foreign languages."],
["harass","To keep annoying or upsetting someone.","Don't harass the animals at the zoo."],
["interrupt","To stop someone while they are speaking or doing something.","Please don't interrupt me."],
["knowledge","What you know and understand.","Her knowledge of dinosaurs is amazing."],
["mischievous","Playful and likely to cause small trouble.","The mischievous puppy chewed my shoe."],
["cemetery","A place where dead people are buried.","The old cemetery lies beside the church."],
["sincerely","Honestly; truly.","'Yours sincerely' ends a formal letter."]]],
["Religion and beliefs",[
["belief","Something you think is true.","People have different religious beliefs."],
["tradition","A custom passed down over many years.","Lighting candles is a tradition at Diwali."],
["ceremony","A formal event held for a special occasion.","The wedding ceremony took place in a temple."],
["sacred","Holy; very special in a religion.","The river is sacred to many Hindus."],
["worship","To show love and respect to a god.","Muslims worship in a mosque."],
["festival","A special day or time of celebration.","Eid is an important festival."],
["community","A group of people who live in an area or share something.","The whole community helped after the flood."],
["moral","About what is right and wrong.","The story teaches a moral lesson."],
["respect","Polite and caring attitude towards others.","Treat everyone with respect."],
["diversity","Having many different kinds of people or things.","Our school celebrates diversity."]]],
["Words for writing essays",[
["introduction","The first part of a piece of writing that sets out what it is about.","Your introduction should answer the question briefly."],
["develop","To make an idea grow by adding more detail.","Develop your point with a quotation."],
["furthermore","In addition; also.","Furthermore, the plan is cheap."],
["however","But; despite this.","It was cold; however, we still went out."],
["whereas","While on the other hand.","Cats like to sleep, whereas dogs like to play."],
["consequently","As a result.","He trained hard; consequently, he won."],
["significantly","In an important way.","Prices have risen significantly."],
["quotation","Words copied exactly from a text.","Put the quotation in inverted commas."],
["infer","To work something out from clues.","We can infer that she is lonely."],
["imply","To suggest something without saying it directly.","His smile implied he knew the secret."]]],
["Ancient civilisations",[
["civilisation","A society with its own culture, government and way of life.","Ancient Egypt was a great civilisation."],
["pharaoh","A ruler of ancient Egypt.","The pharaoh was buried in a pyramid."],
["democracy","A system where people vote for their government.","Democracy began in ancient Athens."],
["architecture","The design of buildings.","Greek architecture uses tall columns."],
["artefact","An object made by people long ago.","The museum displays Roman artefacts."],
["archaeologist","A person who studies the past by digging up remains.","The archaeologist found a buried coin."],
["mythology","Traditional stories about gods and heroes.","Zeus is a god in Greek mythology."],
["philosopher","A person who thinks deeply about life and ideas.","Socrates was a famous philosopher."],
["hieroglyphics","Writing that uses pictures as symbols.","Egyptians wrote in hieroglyphics."],
["inscription","Words carved into stone or metal.","The inscription on the tomb was hard to read."]]],
["Chemistry basics",[
["element","A substance made of only one type of atom.","Oxygen is an element."],
["compound","A substance made of two or more elements joined together.","Water is a compound of hydrogen and oxygen."],
["mixture","Substances mixed together but not joined chemically.","Salty water is a mixture."],
["atom","The smallest part of an element.","Everything is made of atoms."],
["particle","A very small piece of matter.","Particles in a gas move quickly."],
["dissolve","To mix into a liquid and seem to disappear.","Sugar dissolves in tea."],
["solution","A liquid with something dissolved in it.","Salt solution is used in the experiment."],
["filtration","Separating a solid from a liquid using a filter.","We used filtration to remove the sand."],
["reaction","A change in which new substances are made.","Burning is a chemical reaction."],
["acid","A substance with a pH less than 7.","Lemon juice is a weak acid."]]],
["Space and the universe",[
["universe","Everything that exists, including all space and stars.","The universe is incredibly large."],
["galaxy","A huge group of stars.","We live in the Milky Way galaxy."],
["orbit","The curved path of an object around a star or planet.","The Earth orbits the Sun."],
["satellite","An object that moves around a planet.","The Moon is Earth's natural satellite."],
["astronaut","A person trained to travel into space.","The astronaut walked on the Moon."],
["telescope","An instrument that makes faraway objects look closer.","We saw Saturn's rings through a telescope."],
["comet","A ball of ice and dust that travels round the Sun with a glowing tail.","Halley's Comet returns about every 76 years."],
["eclipse","When one object in space blocks the light from another.","A solar eclipse darkened the sky."],
["solar","To do with the Sun.","Solar panels turn sunlight into electricity."],
["axis","An imaginary line around which something spins.","The Earth spins on its axis once a day."]]],
["Tricky spellings 4",[
["acquire","To get or gain something.","She acquired a taste for olives."],
["conscious","Awake and aware.","He was conscious after the fall."],
["existence","The state of being real or alive.","Scientists doubt the existence of the monster."],
["fascinate","To interest someone very much.","Volcanoes fascinate me."],
["hygiene","Keeping yourself and things clean to stay healthy.","Good hygiene stops germs spreading."],
["lightning","A flash of light in the sky during a storm.","Lightning lit up the hills."],
["neighbour","A person who lives near you.","Our neighbour waters our plants."],
["occurrence","Something that happens.","Snow in April is a rare occurrence."],
["privilege","A special advantage or right.","It was a privilege to meet the author."],
["vehicle","Something used to carry people or goods, like a car.","No vehicles are allowed in the park."]]],
["Citizenship",[
["citizen","A person who belongs to a country.","Every citizen has rights."],
["rights","Things everyone should be allowed to have or do.","Children have the right to education."],
["law","A rule made by the government that everyone must follow.","It is against the law to steal."],
["election","When people vote to choose a leader.","The general election is next year."],
["vote","To show your choice in an election.","Everyone in the class voted for a captain."],
["equality","Being equal in rights and chances.","They campaigned for equality."],
["justice","Fair treatment.","The court made sure justice was done."],
["volunteer","A person who works without being paid.","She volunteers at the animal shelter."],
["campaign","A planned set of actions to achieve something.","The campaign raised money for the hospital."],
["responsibility","A duty to do something or to care for someone.","Looking after a pet is a big responsibility."]]],
["Words from Latin and Greek",[
["biography","The story of a person's life written by someone else.","I read a biography of Marie Curie."],
["autobiography","The story of a person's life written by that person.","Her autobiography tells of her childhood."],
["telephone","A device for talking to someone far away.","The word telephone comes from 'tele' (far) and 'phone' (sound)."],
["photograph","A picture made with a camera.","Photograph comes from 'photo' (light) and 'graph' (drawing)."],
["geography","The study of the Earth and its features.","Geography comes from 'geo', which means earth."],
["transport","To carry from one place to another.","Lorries transport food across the country."],
["aquatic","Living in or near water.","Frogs are partly aquatic."],
["chronology","The order in which events happened.","Chronology comes from 'chrono', which means time."],
["manuscript","A handwritten document or book.","The monk copied the manuscript by hand."],
["thermometer","An instrument for measuring temperature.","The thermometer showed 21 degrees."]]],
["Words for the environment",[
["pollution","Harmful things in the air, water or land.","Traffic causes air pollution."],
["recycle","To use again or make into something new.","We recycle paper and plastic."],
["renewable","Able to be replaced naturally.","Solar power is renewable energy."],
["conservation","Protecting nature and wildlife.","Conservation saved the red kite."],
["habitat","The natural home of a plant or animal.","Rainforests are a habitat for many species."],
["species","A group of living things of the same kind.","The tiger is an endangered species."],
["endangered","At risk of dying out.","The panda was once endangered."],
["emissions","Gases sent into the air.","Cars produce carbon emissions."],
["deforestation","Cutting down large areas of forest.","Deforestation destroys habitats."],
["biodiversity","The variety of living things in an area.","Hedgerows increase biodiversity."]]],
["Journeys and exploration",[
["expedition","A long journey made for a special purpose.","The expedition reached the South Pole."],
["navigate","To find your way.","Sailors used the stars to navigate."],
["voyage","A long journey by sea or in space.","The voyage across the Atlantic took weeks."],
["discovery","Finding something for the first time.","The discovery of penicillin saved lives."],
["territory","An area of land belonging to someone.","The explorers entered unknown territory."],
["horizon","The line where the land or sea seems to meet the sky.","A ship appeared on the horizon."],
["peril","Serious danger.","The crew faced great peril in the storm."],
["endurance","The ability to keep going through difficulty.","The journey tested their endurance."],
["remote","Far away from towns and people.","They camped on a remote island."],
["destination","The place someone is travelling to.","We reached our destination at noon."]]],
["Tricky spellings 5",[
["accidentally","By accident; not on purpose.","I accidentally deleted my work."],
["category","A group of things of the same type.","Sort the animals into each category."],
["desperate","Feeling there is little hope; needing something very much.","The hikers were desperate for water."],
["familiar","Well known to you.","His face looked familiar."],
["interfere","To get involved when you are not wanted.","Don't interfere with the experiment."],
["leisure","Free time when you are not working.","Reading is my favourite leisure activity."],
["miniature","Very small; a small copy of something.","He collects miniature cars."],
["programme","A show on TV or radio; a plan of events.","The programme starts at seven."],
["queue","A line of people waiting.","We stood in a queue for tickets."],
["thorough","Careful and complete.","Give the room a thorough clean."]]],
["Looking back on the year",[
["progress","Movement towards a goal; improvement.","I have made good progress in maths."],
["improve","To make or become better.","Reading every day will improve your vocabulary."],
["challenge","Something difficult that tests you.","The hardest puzzle was a real challenge."],
["confidence","Belief in yourself.","Performing on stage gave me confidence."],
["effort","The energy you put into doing something.","She put a lot of effort into her project."],
["target","A goal that you aim to reach.","My target is to read twenty books."],
["perseverance","Continuing to try even when it is hard.","Perseverance helped him learn to swim."],
["accomplish","To finish something successfully.","We accomplished everything on the list."],
["ambition","Something you really want to achieve.","Her ambition is to become a vet."],
["celebrate","To do something enjoyable for a special reason.","We celebrated the end of term."]]],
];
if(typeof module!=="undefined"&&module.exports)module.exports={WEEK1,WEEK_WORDS};
